name: Build and Push Docker Image with Version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Get latest version
      id: get_latest_version
      run: echo "VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
    
    - name: Extract major and minor versions
      id: extract_versions
      run: |
        MAJOR=$(echo $VERSION | cut -d. -f1)
        MINOR=$(echo $VERSION | cut -d. -f2)
        NEXT_MINOR=$((MINOR + 1))
        NEXT_VERSION="${MAJOR}.${NEXT_MINOR}"
        echo "NEXT_VERSION=${NEXT_VERSION}" >> $GITHUB_ENV
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push Docker Image
      run: |
        docker build -t saluteslim/versiontest:${{ env.NEXT_VERSION }} .
        docker push saluteslim/versiontest:${{ env.NEXT_VERSION }}
