name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set version
      id: version
      run: echo "VERSION=$(date +'%Y%m%d%H%M%S')-${GITHUB_REF/refs\/heads\//}" >> $GITHUB_ENV

      #below tags it as => saluteslim/versiontest:20230817110228-main
      #"VERSION=$(date +'%Y%m%d%H%M%S')-${GITHUB_REF/refs\/heads\//}" >> $GITHUB_ENV

      #below tags it as => saluteslim/versiontest:0faf674
      #"VERSION=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push Docker Image
      run: |
        docker build -t versiontest:${{ env.VERSION }} .
        docker tag versiontest:${{ env.VERSION }} saluteslim/versiontest:${{ env.VERSION }}
        docker push saluteslim/versiontest:${{ env.VERSION }}
