name: Build and Push Docker Image

on:
  push:
    branches:
      - main # You can change this to match the branch you want to build from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetching all commits to facilitate versioning

    - name: Bump version and create a tag
      id: bump_version
      run: |
        # Get latest tag
        LATEST_TAG=$(git describe --tags --abbrev=0)
        # Extract parts of the version
        MAJOR=$(echo $LATEST_TAG | cut -d. -f1)
        MINOR=$(echo $LATEST_TAG | cut -d. -f2)
        PATCH=$(echo $LATEST_TAG | cut -d. -f3)
        # Increment patch version by one
        NEW_PATCH=$((PATCH + 1))
        # Construct new version
        VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
        # Tag in git
        git tag $VERSION
        # Echo version for later steps
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/versiontest:${{ env.VERSION }}
        push: true
