name: Build and Push Docker Image with Version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Get latest version
      id: get_latest_version
      run: echo "VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
    
    - name: Calculate next version
      id: calculate_next_version
      run: echo "NEXT_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++; print}')" >> $GITHUB_ENV
    
    - name: Set next version
      id: set_next_version
      run: echo "NEXT_VERSION=${NEXT_VERSION}" >> $GITHUB_ENV
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push Docker Image
      run: |
        docker build -t versiontest:${{ env.NEXT_VERSION }} .
        docker tag versiontest:${{ env.NEXT_VERSION }} saluteslim/versiontest:${{ env.NEXT_VERSION }}
        docker push saluteslim/versiontest:${{ env.NEXT_VERSION }}
