name: Build and Push Docker Image with Version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Get latest version
      id: get_latest_version
      run: echo "VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push Docker Image
      run: |
        docker build -t saluteslim/versiontest:${{ env.VERSION }} .
        docker push saluteslim/versiontest:${{ env.VERSION }}
